export const GET_JSON_PRODUCT_DATA = "GET_JSON_PRODUCT_DATA";

export const SUCCESS_JSON_PRODUCT_SHOWN = "SUCCESS_JSON_PRODUCT_SHOWN";
export const FAILURE_JSON_PRODUCT_SHOWN = "FAILURE_JSON_PRODUCT_SHOWN";
export const LOADING_JSON_PRODUCT_SHOWN = "LOADING_JSON_PRODUCT_SHOWN";
export const GET_JSON_MEN_DATA = "GET_JSON_MEN_DATA";
export const GET_JSON_WOMEN_DATA = "GET_JSON_WOMEN_DATA";
export const GET_FILTER_PRODUCT = "GET_FILTER_PRODUCT";
export const GET_SORTING_PRODUCT = "GET_SORTING_PRODUCT";
export const PARTICULAR_DATA = "PARTICULAR_DATA";
export const ADD_CHECKOUT_ADDRESS= "ADD_CHECKOUT_ADDRESS";
export const ADD_PAYMENT_DETAILS= "ADD_PAYMENT_DETAILS";
export const ADD_HANDLE_BUY= "ADD_HANDLE_BUY";

